version: dev # Version placeholder (overridden by workflow)
markdown: kramdown
style: cobalt

repository: gmamaladze/gmamaladze.github.io
baseurl: ""

keep_files:
  - George_Mamaladze_CV.pdf

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - tmp/
  - vendor/