markdown: kramdown
style: cobalt

repository: gmamaladze/gmamaladze.github.io
baseurl: ""

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - tmp/
  - vendor/
  - cv-printable.typ